# Generated by Django 5.0.4 on 2024-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enggapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bonus',
            new_name='competency',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='hire_date',
            new_name='completetion_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name_of_candidate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='trackLevel',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='certification_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='certification_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='certification_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='course_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_notification_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_of_pn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='validity_of_certificate',
            field=models.DateField(auto_now=True),
        ),
    ]
